title: King Lyn - 内观外达看世界
description: PHPer
name: King Lyn
markdown: redcarpet
encoding: "utf-8"
permalink: blog/:year/:month/:day/:title.html

# --using code highlighting on github and linux
highlighter: pygments

# --using code highlighting on windows
# pygments: false
# highlighter: rouge

extensions: [fenced_code_blocks]
rss_path: feed.xml
BASE_PATH: http://www.kinglyn.com
img_url: /images

comments :
  provider : uyan
